POS/Controllers/AdminController.cs
namespace POS.Controllers
{
    #region

    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using POS.Domain.Abstract;
    using POS.Domain.Model;

    #endregion

    public class AdminController : ControllerBase
    {
        #region Fields

        private readonly IProductRepository _productRepository;

        #endregion

        #region Constructors and Destructors

        public AdminController(IProductRepository productRepo)
        {
            _productRepository = productRepo;
        }

        #endregion

        #region Public Methods and Operators

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        public ViewResult CreateCategory()
        {
            return View("EditCategory", new Category());
        }

        public ViewResult CreateParentCategory()
        {
            return View("EditParentCategory", new ParentCategory());
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == id);
            if (product != null)
            {
                _productRepository.DeleteProduct(product);
                TempData["message"] = string.Format("Product {0} was deleted", product.Name);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteCategory(int id)
        {
            Category category = _productRepository.Categories.FirstOrDefault(p => p.CategoryId == id);
            if (category != null)
            {
                _productRepository.DeleteCategory(category);
                TempData["message"] = string.Format("Category {0} was deleted", category.Name);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteParentCategory(int id)
        {
            ParentCategory parentCategory =
                _productRepository.ParentCategories.FirstOrDefault(p => p.ParentCategoryId == id);
            if (parentCategory != null)
            {
                _productRepository.DeleteParentCategory(parentCategory);
                TempData["message"] = string.Format("Parent-Category {0} was deleted", parentCategory.Name);
            }

            return RedirectToAction("Index");
        }

        public ViewResult Edit(int id)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == id);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }

                _productRepository.SaveProduct(product);
                TempData["message"] = string.Format("Product {0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(product);
            }
        }

        public ViewResult EditCategory(int id)
        {
            Category category = _productRepository.Categories.FirstOrDefault(p => p.CategoryId == id);
            return View(category);
        }

        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _productRepository.SaveCategory(category);
                TempData["message"] = string.Format("Category {0} has been saved", category.Name);
                return RedirectToAction("IndexCategory");
            }
            else
            {
                // there is something wrong with the data values
                return View(category);
            }
        }

        public ViewResult EditParentCategory(int id)
        {
            ParentCategory parentCategory =
                _productRepository.ParentCategories.FirstOrDefault(p => p.ParentCategoryId == id);
            return View(parentCategory);
        }

        [HttpPost]
        public ActionResult EditParentCategory(ParentCategory parentCategory)
        {
            if (ModelState.IsValid)
            {
                _productRepository.SaveParentCategory(parentCategory);
                TempData["message"] = string.Format("Parent {0} has been saved", parentCategory.Name);
                return RedirectToAction("IndexParentCategory");
            }
            else
            {
                // there is something wrong with the data values
                return View(parentCategory);
            }
        }

        public ViewResult Index()
        {
            return View(_productRepository.Products);
        }

        public ViewResult IndexCategory()
        {
            return View(_productRepository.Categories);
        }

        public ViewResult IndexParentCategory()
        {
            return View(_productRepository.ParentCategories);
        }

        #endregion
    }
}

POS/Controllers/CartController.cs
namespace POS.Controllers
{
    #region

    using System.Linq;
    using System.Web.Mvc;

    using POS.Domain.Abstract;
    using POS.Domain.ApplicationService;
    using POS.Domain.Model;
    using POS.Domain.Properties;
    using POS.Models;

    #endregion

    public class CartController : Controller
    {
        #region Fields

        //private readonly CartApplicationService _cartApplicationService;

        private readonly ICartApplicationService _cartApplicationService;

        private readonly IProductRepository _repository;

        #endregion

        #region Constructors and Destructors

        public CartController(IProductRepository productRepository, /*CartApplicationService cartApplicationService*/ ICartApplicationService cartApplicationService)
        {
            this._repository = productRepository;
            this._cartApplicationService = cartApplicationService;
        }

        #endregion

        #region Public Methods and Operators

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = this._repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError(string.Empty, Resources.EmptyCartError);
            }

            if (ModelState.IsValid)
            {
                _cartApplicationService.Process(cart, shippingDetails);
                return View("Completed");
            }

            return View(shippingDetails);
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = this._repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Summary(Cart cart)
        {
            return View(cart);
        }

        #endregion
    }
}

POS/Controllers/MasterController.cs
using System.Web.Mvc;
using POS.Domain.Abstract;

namespace POS.Controllers
{
    public class MasterController : Controller
    {
        #region Fields

        public IProductRepository ProductRepository;

        public IEstablishmentRepository EstablishmentRepository;

        #endregion

        #region Constructors and Destructors

        public MasterController(IProductRepository productRepo)
        {
            ProductRepository = productRepo;
        }

        public MasterController(IEstablishmentRepository establishmentRepo)
        {
            EstablishmentRepository = establishmentRepo;
        }

        #endregion
    }
}

POS/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using POS.Domain.Abstract;
using POS.Domain.Model;

namespace POS.Controllers
{
    #region

    

    #endregion

    public class ProductController : ControllerBase
    {
        #region Fields

        private readonly IProductRepository _productRepository;

        #endregion

        #region Constructors and Destructors

        public ProductController(IProductRepository productRepo)
        {
            _productRepository = productRepo;
        }

        #endregion

        #region Public Methods and Operators

        public ActionResult Categories()
        {
            return PartialView(_productRepository.Categories);
        }

        public ActionResult CategoryList(int parentCategory)
        {
            IEnumerable<Category> categoryList = _productRepository.Categories.Where(p => p.ParentCategoryId == parentCategory);
            return PartialView("CategoryList", categoryList);
        }

        public FileContentResult GetImage(int productid)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productid);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ViewResult List()
        {
            // lists everything (categories + products) for demo purposes
            return View(_productRepository.Categories);
        }

        public ActionResult ParentCategories()
        {
            return View(_productRepository.ParentCategories);
        }

        public ActionResult ProductList(int category)
        {
            IEnumerable<Product> productList = _productRepository.Products.Where(p => p.CategoryId == category);
            return PartialView("ProductList", productList);
        }

        #endregion
    }
}

POS/Views/Shared/ProductSummary.cshtml
@model POS.Domain.Entities.Product
           
<div class = "item">
    <h3>@Model.Name</h3>
    @Model.Description
    @Model.Category.Name
    <h4>@Model.Price.ToString("c")</h4>
</div>

POS/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Admin.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

POS/Views/Shared/_Layout.cshtml
@using Telerik.Web.Mvc.UI
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <!--<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />-->
    <link href="@Url.Content("~/Content/imports.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    @Html.Telerik().StyleSheetRegistrar().DefaultGroup(group => group.Add("telerik.common.css").Add("telerik.vista.css"))
    @RenderSection("HeadContent", required:false)
    @Html.Telerik().ScriptRegistrar()
</head>
    <body style="background: #ebffef;">
        <section class="drawer" id="fromtop">
            <div class="container">
                <div class="row">
                    <i class="two columns">
                        <div id="logindisplay">
                            @Html.Partial("_LogOnPartial")
                        </div>
                    </i>
                    <i class="two columns"><p>@Html.ActionLink("OrderDetails Index", "Index", "OrderDetails")</p></i>
                    <i class="two columns"><p>@Html.ActionLink("OrderDetailsFullOrders", "FullOrders", "OrderDetails")</i>
                </div>
                <div class="row">
                    <i class="two columns"><p>@Html.ActionLink("OrderDetailsMaster", "Master", "OrderDetails")</i>
                    <i class="two columns"><p>@Html.ActionLink("EstablishmentSalesReport (must append an int)", "EstablishmentSalesReport", "OrderDetails")</i>
                </div>
            </div>
        </section>
        @{Html.RenderAction("Summary", "Cart");}
        
        <div class="row">
            <h2>Navigation</h2>
            <nav class="pretty navbar clearfix" id="prettynav">
                <a href="#" class="toggle" data-for="#basicnav > ul"><img src="@Url.Content("~/Content/img/icon_nav_toggle.gif")" /></a>
                <ul>
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                        <div class="dropdown">
                            <ul>
                                <li><a href="#">Dropdown item</a></li>
                                <li><a href="#">Dropdown item</a></li>
                                <li><a href="#">Dropdown item</a></li>
                                <li><a href="#">Dropdown item</a></li>
                            </ul>
                        </div>
                    </li>
                    <li>@Html.ActionLink("Parent Categories", "ParentCategories", "Product")</li>
                    <li>@Html.ActionLink("Product Admin", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Establishment Admin", "Index", "Establishment")</li>
                    <li>
                        <div class="field">
                            <p class="text search oval"><input type="search" placeholder="Search" /></p>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="container">
                    <article class="row drawertoggle">
                        <p class="three columns alpha"><a href="#" class="toggle" data-for=".drawer#fromtop">Open Drawer Up Top</a></p>
                    </article>
            </div>
        </div>

        <div class="page">
            <section id="main">
                @RenderBody()
            </section>
            <footer>
                
            </footer>
        </div>
        
    </body>
    <script src="@Url.Content("~/Scripts/gumbyScripts/libs/gumby.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/gumbyScripts/plugins.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/gumbyScripts/main.js")" type="text/javascript"></script>
</html>

POS/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}