POS/Controllers/EstablishmentController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Domain.Abstract;
using POS.Domain.Model;

namespace POS.Controllers
{
    public class EstablishmentController : ControllerBase
    {
        #region Fields

        private readonly IEstablishmentRepository _establishmentRepository;

        #endregion

        #region Constructors and Destructors

        public EstablishmentController(IEstablishmentRepository establishmentRepo)
        {
            _establishmentRepository = establishmentRepo;
        }

        #endregion

        public ViewResult Index()
        {
            return View(_establishmentRepository.Establishments);
        }

        public ViewResult Edit(int id)
        {
            Establishment establishment =
                _establishmentRepository.Establishments.FirstOrDefault(p => p.EstablishmentId == id);
            return View(establishment);
        }

        [HttpPost]
        public ActionResult Edit(Establishment establishment, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    establishment.ImageMimeType = image.ContentType;
                    establishment.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(establishment.ImageData, 0, image.ContentLength);
                }

                _establishmentRepository.SaveEstablishment(establishment);
                // TODO: _establishmentRepository.Add(establishment);
                TempData["message"] = string.Format("Establishment {0} has been saved", establishment.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(establishment);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Establishment establishment = _establishmentRepository.Establishments.FirstOrDefault(p => p.EstablishmentId == id);
            if (establishment != null)
            {
                _establishmentRepository.DeleteEstablishment(establishment);
                TempData["message"] = string.Format("Establishment {0} was deleted", establishment.Name);
            }

            return RedirectToAction("Index");
        }

        public ViewResult Create()
        {
            return View("Edit", new Establishment());
        }
    }
}

POS/Controllers/EstablishmentManagerController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Domain.Abstract;
using POS.Domain.Model;

namespace POS.Controllers
{
    public class EstablishmentManagerController : ControllerBase
    {
        #region Fields

        private readonly IEstablishmentRepository _establishmentRepository;

        #endregion

        #region Constructors and Destructors

        public EstablishmentManagerController(IEstablishmentRepository establishmentRepo)
        {
            _establishmentRepository = establishmentRepo;
        }

        #endregion

        public ViewResult Index()
        {
            return View(_establishmentRepository.Establishments);
        }

        public ViewResult Edit(int id)
        {
            Establishment establishment =
                _establishmentRepository.Establishments.FirstOrDefault(p => p.EstablishmentId == id);
            return View(establishment);
        }

        [HttpPost]
        public ActionResult Edit(Establishment establishment, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    establishment.ImageMimeType = image.ContentType;
                    establishment.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(establishment.ImageData, 0, image.ContentLength);
                }

                _establishmentRepository.SaveEstablishment(establishment);
                TempData["message"] = string.Format("Establishment {0} has been saved", establishment.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(establishment);
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Establishment establishment = _establishmentRepository.Establishments.FirstOrDefault(p => p.EstablishmentId == id);
            if (establishment != null)
            {
                _establishmentRepository.DeleteEstablishment(establishment);
                TempData["message"] = string.Format("Establishment {0} was deleted", establishment.Name);
            }

            return RedirectToAction("Index");
        }

        public ViewResult Create()
        {
            return View("Edit", new Establishment());
        }
    }
}

POS/Views/Establishment/Edit.cshtml
@model POS.Domain.Model.Establishment

@{
    ViewBag.Title = "Establishment Manager: Edit" + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>
@using (Html.BeginForm("Edit", "Establishment", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.EditorForModel()

    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "EstablishmentManager", new { Model.EstablishmentId })" alt="thumbnail" />
        }
        <div>Upload new image: <input type="file" name="Image" /></div>
    </div>
    <input type="submit" value="Save" />
    @Html.ActionLink("Cancel and return to the list", "Index")
}

POS/Views/Establishment/Index.cshtml
@using POS.Domain.Model
@model IEnumerable<Establishment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Locations</h1>
<table class="Grid">
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    @foreach (Establishment item in Model)
    {
        <tr>
            <td>@Html.ActionLink(item.Name, "Edit", new { id = item.EstablishmentId })</td>
            <td>
                @using (Html.BeginForm("Delete", "Establishment"))
                {
                    @Html.Hidden("id", item.EstablishmentId)
                    <input type="submit" value="Delete"/>
                }
            </td>
        </tr>
    }
</table>
<p>@Html.ActionLink("Add a new establishment", "Create")</p>